name = "chatgpt-proxy-worker"
main = "src/index.ts"
compatibility_date = "2024-06-06"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "chatgpt"
database_id = "881d58b9-f6b5-49e9-a19b-d860670c3213"


[vars]
ADMIN_USERNAME = 'dairoot' # 管理后台账号密码 （请更改此密码）
ADMIN_PASSWORD = '8f5654bfaf2ea505' 
